defaults: &defaults
  docker:
    - image: circleci/node:10.6
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
            - tmp
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Initialize Code Climate
          command: |
            mkdir -p ci-tools/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./ci-tools/codeclimate-reporter
            chmod +x ./ci-tools/codeclimate-reporter

      - run:
          name: Run Tests
          command: |
            ./ci-tools/codeclimate-reporter before-build
            npm run test:ci
            ./ci-tools/codeclimate-reporter format-coverage -t lcov -o ci-tools/codeclimate.json coverage/lcov.info
            ./ci-tools/codeclimate-reporter after-build --coverage-input-type lcov --exit-code $?

      - run:
          name: Update CodeClimate
          command: |
            ./ci-tools/codeclimate-reporter sum-coverage ci-tools/codeclimate.json -p $CIRCLE_NODE_TOTAL -o ci-tools/codeclimate.total.json
            ./ci-tools/codeclimate-reporter upload-coverage -i ci-tools/codeclimate.total.json

      - run: npm audit # enable when log4js audits successfully with loggly

      - store_artifacts:
          path: coverage
          destination: coverage
      - store_artifacts:
          path: reports
          destination: reports
      - store_test_results:
          path: reports/junit
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
